# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
